AxelsBud/Controllers/hjolastandarController.cs
using Newtonsoft.Json;
using System.Collections.Generic;
using System.IO;
using System.Web.Mvc;
using AxelsBud.Models;

namespace AxelsBud.Controllers
{
    public class hjolastandarController : Controller
    {
        // GET: hjolastandar
        public ActionResult hjolastandar()
        {
            var result = new hjolastandar()
            {

            };
            return View(result);
        }
    }
}

AxelsBud/Controllers/krakkarnirController.cs
using Newtonsoft.Json;
using System.Collections.Generic;
using System.IO;
using System.Web.Mvc;
using AxelsBud.Models;

namespace AxelsBud.Controllers
{

    public class krakkarnirController : Controller
    {
        //Global variable
        public static string[] names = new string[100];
        public static string[] verd = new string[100];
        public static string[] mynd = new string[100];
        public static string[] lysing = new string[100];
        public static string[] ids = new string[100];
        // GET: krakkarnir
        public ActionResult krakkar()
        {
           
            LoadJson("krakkar");
            var results = new bjollur()
            {
                lysingar = lysing,
                myndir = mynd,
                nofn = names,
                verdin = verd,
                audkenin = ids
            };
            return View(results);
        }
        
        //Load the Json
        public void LoadJson(string sub)
        {
            string path = HttpContext.Server.MapPath("~/App_Data/" + sub + ".json");
            using (StreamReader r = new StreamReader(path))
            {
                string json = r.ReadToEnd();
                var items = JsonConvert.DeserializeObject<List<Item>>(json);
                int counter = 0;
                foreach (var data in items)
                {
                    names[counter] = data.Name;
                    verd[counter] = data.verd;
                    lysing[counter] = data.lysing;
                    mynd[counter] = data.mynd;
                    ids[counter] = data.ID;
                    counter = counter + 1;
                }

            }
        }
    }
}

AxelsBud/Controllers/vidgerdController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AxelsBud.Controllers
{
    public class vidgerdController : Controller
    {
        // GET: vidgerd
        public ActionResult vidgerd()
        {
            
            return View();
        }
    }
}

AxelsBud/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @* favicon stuff *@
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#000000">
    <meta name="theme-color" content="#000000">
    @* favicon end *@
    <link href="~/MyCss/cssGrid.css" rel="stylesheet" type="text/css" />
    <link href="~/MyCss/hedder.css" rel="stylesheet" type="text/css" />
</head>

<body>
    <div class="head_wrapper head_background"></div>
    <div class="head_wrapper">
        <div class="head_container">
            @*<div class="AxelsBudTextinn">@Html.ActionLink("Axelsbúð", "", "")</div>*@
            <div class="head_img_frame">
                <img src="~/images/axelsbud1.png" />
            </div>
            <div class="head_img_frame">
                <img src="~/images/frontTester.png" />
            </div>
            <div class="head_img_frame">
                <img src="~/images/axelsbud2.png" />
            </div>
        </div>
    </div>
    <div class="nav_wrapper" @*class="navbar-inverse navbar-fixed-top"*@>
        <div class="nav_bar" id="myDIV">
            <div class="nav_head_burger_wrapper">

                <div class="nav_logo_wrapper navbar-header">
                    @*<img src="~/images/logo.png" class="nav_logo" />*@
                    @Html.ActionLink("Axelsbúð", "Index", "Home", new { area = "" }, new { @class = "nav_button nav_button_home" })
                </div>
                <button type="button" class="nav_hamburger" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="nav_links navbar-collapse collapse">
                <ul class="nav_links_buttons">
                    <li class="nav_button">@Html.ActionLink("Reiðhjól", "", "fullordinshjol")</li>
                    <li class="dropdown nav_button">
                        <a class="" href="/aukahlutir">Aukahlutir</a>
                        <div class="dropdown_content">
                            <div>@Html.ActionLink("Bjöllur", "", "aukahlutir/bjollur")</div>
                            <div>@Html.ActionLink("Bretti", "", "aukahlutir/bretti")</div>
                            <div>@Html.ActionLink("Bögglaberar", "", "aukahlutir/bogglaberar")</div>
                            <div>@Html.ActionLink("Hraðamælar", "", "aukahlutir/hradamaelar")</div>
                            <div>@Html.ActionLink("Körfur", "", "aukahlutir/korfur")</div>
                            <div>@Html.ActionLink("Ljós", "", "aukahlutir/ljos")</div>
                            <div>@Html.ActionLink("Pumpur", "", "aukahlutir/pumpur")</div>
                            <div>@Html.ActionLink("Standarar", "", "aukahlutir/standarar")</div>
                            <div>@Html.ActionLink("Stýrisendar", "", "aukahlutir/styrisendar")</div>
                            <div>@Html.ActionLink("Vatnsflöskur og statíf", "", "aukahlutir/vatnsfloskur_statif")</div>
                            <div>@Html.ActionLink("Hnakkar", "", "aukahlutir/hnakkar")</div>
                            <div>@Html.ActionLink("Lásar", "", "aukahlutir/lasar")</div>
                        </div>
                    </li>
                    <li class="dropdown nav_button">
                        <a class="" href="/varahlutir">Varahlutir</a>
                        <div class="dropdown_content">
                            <div>@Html.ActionLink("Bremsubúnaður", "", "varahlutir/bremsubunadur")</div>
                            <div>@Html.ActionLink("Gírskiptar", "", "varahlutir/girskiptingar")</div>
                            <div>@Html.ActionLink("Keðju og gírhlífar", "", "varahlutir/kedjur_girhlifar")</div>
                            <div>@Html.ActionLink("Gjarðir", "", "varahlutir/gjardir")</div>

                        </div>
                    </li>
                    <li class="nav_button">@Html.ActionLink("Krakkarnir", "", "krakkarnir")</li>
                    <li class="nav_button">@Html.ActionLink("Hjólastandar", "", "hjolastandar")</li>
                    <li class="nav_button">@Html.ActionLink("Hjóla viðgerðir", "", "vidgerd")</li>
                    <li class="nav_button">@Html.ActionLink("Kertastjakar", "", "kertastjakar")</li>
                    <li class="dropdown nav_button">
                        <a class="">Um Axelsbúð</a>
                        <div class="dropdown_content">
                            <div>@Html.ActionLink("Sagan um Axelsbúð", "", "umAxelsbud")</div>
                            <div>@Html.ActionLink("Heimildarmynd", "", "heimildarmynd")</div>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="body-content">
        @RenderBody()
    </div>

    @* ATH veit ekki afh. en það er ólokað div úr þessu render boddy.......  *@

    <div class="footer_wrapper">
        <div class="footer_bar">
            @*<div class="footer_element">
                    <a href="https://wego.here.com/iceland/akraneskaupsta%C3%B0ur/street-square/merkiger%C3%B0i-2--loc-dmVyc2lvbj0xO3RpdGxlPU1lcmtpZ2VyJUMzJUIwaSsyO2xhbmc9aXM7bGF0PTY0LjMxOTUyNjY3MjM2MzI4O2xvbj0tMjIuMDg0MTU5ODUxMDc0MjI7c3RyZWV0PU1lcmtpZ2VyJUMzJUIwaTtob3VzZT0yO2NpdHk9QWtyYW5lc2thdXBzdGElQzMlQjB1cjtwb3N0YWxDb2RlPTMwMDtjb3VudHJ5PUlTTDtkaXN0cmljdD1Ba3JhbmVzO2NvdW50eT1WZXN0dXJsYW5kO2NhdGVnb3J5SWQ9YnVpbGRpbmc7c291cmNlU3lzdGVtPWludGVybmFsO25sYXQ9NjQuMzE5NjQxMTEzMjgxMjU7bmxvbj0tMjIuMDg0MDcwMjA1Njg4NDc3O3Bkc0NhdGVnb3J5SWQ9OTAwLTkzMDAtMDAwMA?map=64.31953,-22.08416,15,normal&fb_locale=en_US%22%3E%3Ci%20class%3D%22fa%20fa-angle-double-right&x=ep">
                        <p><div class="footer_img">
                            <object viewBox="0 0 100 100" data="/images/location-pin.svg" type="image/svg+xml" class="footer_svg">
                                <img src="~/images/location-pin.png" />
                            </object>
                            </div>
                        Merkigerði 2</p>
                    </a>
                </div>*@

            @*<div class="footer_element">
                    <img src="~/images/home.svg"class="footer_img" />
                    <p>300 Akranes</p>
                </div>*@
            <div class="footer_element">
                <a href="tel:4311531">
                    <img src="~/images/telephone.svg" class="footer_img" />
                    <p>431-1531</p>
                </a>
            </div>
            <div class="footer_element">
                <a href="tel:8961979">
                    <img src="~/images/mobile-phone.svg" class="footer_img" />
                    <p>896-1979</p>
                </a>
            </div>
            <div class="footer_element">
                <a href="mailto:Axelg@simnet.is">
                    <img src="~/images/mail.svg" class="footer_img" />
                    <p>Axelg@simnet.is</p>
                </a>
            </div>
            <div class="footer_element">
                <a href="https://wego.here.com/iceland/akraneskaupsta%C3%B0ur/street-square/merkiger%C3%B0i-2--loc-dmVyc2lvbj0xO3RpdGxlPU1lcmtpZ2VyJUMzJUIwaSsyO2xhbmc9aXM7bGF0PTY0LjMxOTUyNjY3MjM2MzI4O2xvbj0tMjIuMDg0MTU5ODUxMDc0MjI7c3RyZWV0PU1lcmtpZ2VyJUMzJUIwaTtob3VzZT0yO2NpdHk9QWtyYW5lc2thdXBzdGElQzMlQjB1cjtwb3N0YWxDb2RlPTMwMDtjb3VudHJ5PUlTTDtkaXN0cmljdD1Ba3JhbmVzO2NvdW50eT1WZXN0dXJsYW5kO2NhdGVnb3J5SWQ9YnVpbGRpbmc7c291cmNlU3lzdGVtPWludGVybmFsO25sYXQ9NjQuMzE5NjQxMTEzMjgxMjU7bmxvbj0tMjIuMDg0MDcwMjA1Njg4NDc3O3Bkc0NhdGVnb3J5SWQ9OTAwLTkzMDAtMDAwMA?map=64.31953,-22.08416,15,normal&fb_locale=en_US%22%3E%3Ci%20class%3D%22fa%20fa-angle-double-right&x=ep">
                    <img src="~/images/location-pin.svg" class="footer_img" />
                    <p>Merkigerði 2, 300 Akranes</p>
                </a>
            </div>
            <div class="footer_element">
                <a href="https://www.facebook.com/Axelsb%C3%BA%C3%B0-1469800143236849/">
                    <img src="~/images/icons8-facebook.svg" class="footer_img" />
                    <p>Axelsbúð</p>
                </a>
            </div>

        </div>

    </div>
    @*<div class="row" id="rows">
            <div class="col-md-4">
                <div class="footercolumn">
                   <a href="https://wego.here.com/iceland/akraneskaupsta%C3%B0ur/street-square/merkiger%C3%B0i-2--loc-dmVyc2lvbj0xO3RpdGxlPU1lcmtpZ2VyJUMzJUIwaSsyO2xhbmc9aXM7bGF0PTY0LjMxOTUyNjY3MjM2MzI4O2xvbj0tMjIuMDg0MTU5ODUxMDc0MjI7c3RyZWV0PU1lcmtpZ2VyJUMzJUIwaTtob3VzZT0yO2NpdHk9QWtyYW5lc2thdXBzdGElQzMlQjB1cjtwb3N0YWxDb2RlPTMwMDtjb3VudHJ5PUlTTDtkaXN0cmljdD1Ba3JhbmVzO2NvdW50eT1WZXN0dXJsYW5kO2NhdGVnb3J5SWQ9YnVpbGRpbmc7c291cmNlU3lzdGVtPWludGVybmFsO25sYXQ9NjQuMzE5NjQxMTEzMjgxMjU7bmxvbj0tMjIuMDg0MDcwMjA1Njg4NDc3O3Bkc0NhdGVnb3J5SWQ9OTAwLTkzMDAtMDAwMA?map=64.31953,-22.08416,15,normal&fb_locale=en_US%22%3E%3Ci%20class%3D%22fa%20fa-angle-double-right&x=ep">
                       <p><img src="~/images/location-pin.png" class="mobile_svg" />Merkigerði 2</p>
                    </a>
                    <p><img src="~/images/home.png" class="mobile_svg" />300 Akranes</p>
                </div>
            </div>
            <div class="col-md-4">
                <div class="footercolumn">
                    <a href="tel:4311531"><p><img src="~/images/telephone.png" class="mobile_svg" />Sími: 431-1531</p></a>
                    <a href="tel:8961979"><p><img src="~/images/mobile.png" class="mobile_svg" />Farsími: 896-1979</p></a>
                </div>
            </div>
            <div class="col-md-4">
                <div class="footercolumn">
                    <a href="mailto:secretary@europenaba.org">
                        <p><img src="~/images/mail.png" class="mobile_svg" />Axelg@simnet.is</p>
                    </a>
                </div>
                <div class="footercolumn">
                    <p><a href="https://www.facebook.com/Axelsb%C3%BA%C3%B0-1469800143236849/"><img src="~/images/facebook.png" height="20" width="15" class="mobile_svg" /></a>heimasíða</p>
                </div>
            </div>
        </div>*@

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>
<script>    
    function getLocation() {
        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(showPosition);
        } else {
            x.innerHTML = "Geolocation is not supported by this browser.";
        }
    }

    function showPosition(position) {
        x.innerHTML = "Latitude: " + position.coords.latitude +
            "<br>Longitude: " + position.coords.longitude;
    }
</script>

@* slideshow for images -- *@
<script>
    var myIndex = 0;
    carousel();
    function carousel() {
        var i;
        var x = document.getElementsByClassName("head_img_frame");
        for (i = 0; i < x.length; i++) {
            x[i].style.display = "none";
        }
        myIndex++;
        if (myIndex > x.length) { myIndex = 1 }
        x[myIndex - 1].style.display = "block";
        setTimeout(carousel, 9000);
    }
</script>